server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: xujialin
  redis:
    host: 39.101.178.126
    port: 6379
    password: xujialin123
    database: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xujialin.mapper

