server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://IP地址:3306/Blog
    username:
    password:
  redis:
    host: IP地址
    port: 6379
    password:
    database: 0
  servlet:
    multipart:
      max-request-size: 10MB
      enabled: true
      max-file-size: 5MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.xujialin.mapper


